[TASK-257] 바텀 select sheet 추가
ToyVallet/swifty-frontend pull request #49
Opened 2024-07-05 09:54 UTC by kd02109

- Closes #47  
- radix-ui/react-seect와 연동했을 때 데스크탑 환경에서는 문제없이 동작하지만, 모바일 환경에서 정상적으로 동작하지 않는 버그가 발견되어 아래와 같은 방식을 사용했습니다. 코드는 다음과 같습니다.
```tsx
'use client';

import { BottomSheet } from '@components/common';
import useBottomSheet from '@hooks/use-bottom-sheet';
import BottomArrow from '@icons/bottom-arrow.svg';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
} from '@radix-ui/react-select';
import { Input } from '@swifty/ui';
import cn from 'clsx';
import { useRef, useState } from 'react';

type Props = {
  data: string[];
  label: string;
  defaultValue: string;
};

export default function BottomSelect({ data, label, defaultValue }: Props) {
  const [isOpen, open, close] = useBottomSheet();
  const [value, setValue] = useState<string | undefined>(defaultValue);
  const ref = useRef<HTMLInputElement>(null);

  const onSelectValue = (value: string) => {
    setValue(value);
    close();
  };

  return (
    <>
      <Select
        value={value}
        onValueChange={(value) => {
          onSelectValue(value);
        }}
        onOpenChange={(isOpen) => {
          if (isOpen) {
            open();
            ref.current?.focus();
          } else {
            close();
          }
        }}
        //open
        defaultValue={defaultValue}
      >
        <SelectTrigger asChild>
          {
            <div className="relative w-full">
              <Input
                label={label}
                defaultValue={value}
                ref={ref}
                onClick={(e) => e.preventDefault()}
                type="button"
                className={
                  defaultValue === value
                    ? 'text-swifty-color-500'
                    : 'text-white'
                }
              />
              <BottomArrow className="absolute top-[31px] right-10" />
            </div>
          }
        </SelectTrigger>

        <SelectContent asChild>
          <div>
            <BottomSheet isOpen={isOpen} onDismiss={close}>
              {data.map((item, index) => (
                <Item
                  key={item}
                  value={item}
                  underline={index !== data.length - 1}
                />
              ))}
            </BottomSheet>
          </div>
        </SelectContent>
      </Select>
    </>
  );
}

type ItemProps = {
  value: string;
  underline?: boolean;
} & React.ComponentPropsWithoutRef<'div'>;

function Item({ value, underline, ...props }: ItemProps) {
  return (
    <SelectItem
      value={value}
      className={cn(
        'bg-black text-white text-center text-16 font-medium py-[22px] hover:bg-gray-800 focus:bg-swifty-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-swifty-gray-500',
        underline && 'border-swifty-color-700 border-b-2 border-solid',
      )}
      {...props}
    >
      {value}
    </SelectItem>
  );
}

```

위의 코드로 동작할시 아래 영상과 같은 버그가 발생합니다. 모바일 환경에서 버튼을 꾺눌러야만 실행이 됩니다. 그래서 radix UI를 활용하지 않고 구현했습니다. 

[스위프티.webm](https://github.com/ToyVallet/swifty-frontend/assets/57277708/99c74b4a-2b48-47eb-8e8a-4354ba112f58)

구현 결과 코드는 아래와 같습니다.
```tsx
'use client';

import { BottomSheet } from '@components/common';
import useBottomSheet from '@hooks/use-bottom-sheet';
import BottomArrow from '@icons/bottom-arrow.svg';
import { Input } from '@swifty/ui';
import cn from 'clsx';
import type { ComponentPropsWithoutRef } from 'react';
import { useRef, useState } from 'react';

type Props = {
  data: string[];
  label: string;
  defaultValue: string;
};

export default function BottomSelect({ data, label, defaultValue }: Props) {
  const [isOpen, open, close] = useBottomSheet();
  const [value, setValue] = useState(defaultValue);
  const ref = useRef<HTMLInputElement>(null);

  const onOpen = () => {
    open();
    ref.current?.focus();
  };

  const onSelectValue = (value: string) => {
    setValue(value);
    close();
  };

  return (
    <div>
      <div onClick={onOpen} className="relative">
        <Input
          label={label}
          defaultValue={value}
          ref={ref}
          type="button"
          className={
            defaultValue === value ? 'text-swifty-color-500' : 'text-white'
          }
        />
        <BottomArrow className="absolute top-[31px] right-10" />
      </div>

      <BottomSheet isOpen={isOpen} onDismiss={close}>
        {data.map((item, index) => (
          <Item
            key={item}
            value={item}
            underline={index !== data.length - 1}
            onClick={() => onSelectValue(item)}
          />
        ))}
      </BottomSheet>
    </div>
  );
}

type Item = {
  value: string;
  underline?: boolean;
} & ComponentPropsWithoutRef<'div'>;

function Item({ value, underline, ...props }: Item) {
  return (
    <div
      className={cn(
        'bg-black text-white text-center text-16 font-medium py-[22px] hover:bg-gray-800 focus:bg-swifty-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-swifty-gray-500',
        underline && 'border-swifty-color-700 border-b-2 border-solid',
      )}
      {...props}
    >
      {value}
    </div>
  );
}

```

2024-07-05 10:56 UTC, ho991217 requested changes

2024-07-05 10:56 UTC, ho991217 commented on apps/user-web/src/app/globals.css
> +
이렇게 하면 모든 button 타입 인풋이 영향을 받지 않을까요?

2024-07-05 10:56 UTC, ho991217 commented on packages/ui/src/input/index.tsx
기존 인풋이 고장 났네요... 기존 컴포넌트 고려없이 수정 된 변경내용 같습니다.

2024-07-05 10:56 UTC, ho991217 commented on packages/ui/src/input/index.tsx
> +  label: string;
name은 `react-hook-form`을 위해서 꼭 필요한 속성입니다.
수정하신다면 폼 부분도 함께 수정해주셔야 합니다.

2024-07-05 10:56 UTC, ho991217 commented on apps/user-web/src/components/common/select/index.tsx
> +import BottomArrow from '@icons/bottom-arrow.svg';
arrow 라기 보다는 chevron 아닐까요?
```suggestion
import LowerChevron from '@icons/lower-chevron.svg';
```

2024-07-05 10:56 UTC, ho991217 commented on apps/user-web/src/components/common/select/index.tsx
> +export default function BottomSelect({ data, label, defaultValue }: Props) {
기존 바텀시트를 활용하지 않고 다시 만드신 이유가 있을까요?

2024-07-05 10:56 UTC, ho991217 commented on apps/user-web/src/components/common/select/index.tsx
어디서 이 컴포넌트를 확인해볼 수 있나요?

2024-07-05 10:56 UTC, ho991217 commented on apps/user-web/src/components/common/select/index.tsx
> +        <BottomArrow className="absolute top-[31px] right-10" />
chevron 위치가 피그마와 달라보입니다

2024-07-08 05:09 UTC, kd02109 commented
- 기존 select html tag를 활용해서 bottomsheet를 연결하는 것은 불가능합니다. 다른 ui를 찾아보았을때도, div, button 등을 확장해서 사용한 구조라서 저도 기존 tag를 확장해서 사용을 했습니다. 
- 별도의 라벨을 활용해서 해당 문제를 해결해야 하는 것으로 파악했습니다. 
- /test 경로에서 useHookForm과 기존의 Form 컴포넌트와 연결해서 정상적으로 동작하는 것을 확인했습니다.

2024-07-08 09:53 UTC, ho991217 approved these changes
LGTM ^^

2024-07-08 09:56 UTC, merged