[TASK-13]<root-admin>루트 어드민 유저 상태 변경 기능 추가
ToyVallet/swifty-frontend pull request #9
Opened 2024-06-08 11:55 UTC by kd02109

- 루트 어드민 유저 상태 변경 기능을 추가했습니다. 

노션 링크  : https://www.notion.so/ho991217/136beb23ff0d4b3cad911d8335836ca9

- 유저 상세 페이지
<img width="747" alt="image" src="https://github.com/ToyVallet/swifty-frontend/assets/57277708/b039c939-3b1a-4422-aea1-5732827b3423">

- 유제 페이지 조회
<img width="788" alt="image" src="https://github.com/ToyVallet/swifty-frontend/assets/57277708/33e3a504-fa8b-443f-9b93-ef42d1b177b7">

2024-06-08 23:24 UTC, ho991217 requested changes
짧은 시간 내에 많은 코드를 작성하셨네요! 고생많으셨습니다.

2024-06-08 23:24 UTC, ho991217 commented on apps/root-admin/src/app/(dashboard)/festivals/[id]/data.ts
> +const dynamic = 'force-dynamic';
`export` 만 제거하신 이유가 뭐가요??

2024-06-08 23:24 UTC, ho991217 commented on apps/root-admin/src/app/lib/util/insert-cookie-in-request.ts
요청시 쿠키를 헤더에 자동으로 담기도록 하지 않았나요? 이 함수가 필요한 이유가 궁금합니다.

2024-06-08 23:24 UTC, ho991217 commented on apps/root-admin/src/app/components/user/user-info/user-action.tsx
> +          <Button type="primary" danger size="large">
저희 디자인 시스템에 포함되는 버튼을 사용하는 것이 나을까요? 아니면 antd의 버튼을 사용하는 것이 나을까요?

2024-06-08 23:24 UTC, ho991217 commented on apps/root-admin/src/app/components/user/user-info/user-action.tsx
> +export default function UserActions({
`UserActions`라는 이름은 어떤 컴포넌트인지 알아보기 어려운 것 같습니다!

2024-06-08 23:24 UTC, ho991217 commented on apps/root-admin/src/app/components/user/user-info/user-action.tsx
> +}
```suggestion
import styles from './userInfo.module.css';

interface UserActionsProps {
  userSubId: string;
  status: UserStatus;
  onStatusChange: (newStatus: UserStatus) => void;
}

const USER_STATES = ['activation', 'ban', 'pause'] as const;

export default function UserActions({
  userSubId,
  status,
  onStatusChange,
}: UserActionsProps) {
  const router = useRouter();
  const [errorMessage, setErrorMessage] = useState<null | string>(null);

  const onChangeStatus = async (
    newStatus: UserStatus,
  ) => {
    const apiPath = API_CLIENT.activation[newStatus];
    try {
      await customFetch(apiPath(userSubId), { method: 'PATCH' });
      setErrorMessage(null);
    } catch (err) {
      if (err instanceof Error) {
        setErrorMessage(`Change ${newStatus} : ${err.message}`);
      }
      onStatusChange(prevStatus);
    }
  };

  const deleteUser = async () => {
    await customFetch(API_CLIENT.user(userSubId), { method: 'DELETE' });
    router.replace('/user');
  };

  return (
    <div className={styles.container}>
      <section className={styles.buttonSection}>
        <Popconfirm
          title="계정 삭제"
          description="해당 계정을 삭제하시겠습니까?"
          okText="확인"
          okType="danger"
          cancelText="취소"
          onConfirm={deleteUser}
        >
          <Button type="primary" danger size="large">
            Delete
          </Button>
        </Popconfirm>
        {USER_STATES.map((state) => (
          <Button size="large" onClick={() => onChangeStatus(state)} type="primary">
           {state}
          </Button>
        ))}
        {errorMessage && (
          <span className={styles.errorMessage}>{errorMessage}</span>
        )}
      </section>
    </div>
  );
}
```

이런식으로 매핑하면 훨씬 단순하고 반복이 적은 코드를 만들 수 있을 것 같습니다!

2024-06-09 00:40 UTC, hyunwlee-dev approved these changes
빠르게 하셨네요. 고생하셨습니다!

2024-06-09 00:40 UTC, hyunwlee-dev commented on apps/root-admin/src/app/components/ui/brandcrumb/index.tsx
> +import styles from './brandcrumb.module.css';
파일명 breadcrumb로 수정해주세요!

2024-06-09 06:05 UTC, kd02109 commented on apps/root-admin/src/app/components/user/user-info/user-action.tsx
> +          <Button type="primary" danger size="large">
저도 이 부분을 고민했었는데, 현재 root admin 페이지를 antd로 구현하고 있어서 하나의 디자인 툴을 사용하는게 좋지 않을까 싶어 antd 버튼을 사용했습니다.

2024-06-09 06:05 UTC, kd02109 commented on apps/root-admin/src/app/lib/util/insert-cookie-in-request.ts
그 서버에서 실행하는 경우, 웹페이지에서 쿠키를 가지고 올 수가 없어서 강제로 쿠키를 삽입해서 요청을 보내야 하더라고요

2024-06-09 06:08 UTC, kd02109 commented on apps/root-admin/src/app/(dashboard)/festivals/[id]/data.ts
> +const dynamic = 'force-dynamic';
이 부분은 data.ts에서 route segment config가 정상 동작하지 않아서 export를 제외 했습니다. 아마 해당 코드 자체를 수정해야 할 것 같습니다. 제 부분은 아닌데, 해당 export때문에 에러가 발생해서 일단 지웠습니다.
https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config

2024-06-09 06:40 UTC, ho991217 commented on apps/root-admin/src/app/lib/util/insert-cookie-in-request.ts
그러면 기존 customFetch에 옵션을 추가해서 하나의 함수로 클라이언트와 서버에서 동작하게 하는게 낫지 않나요?

2024-06-09 07:02 UTC, kd02109 commented on apps/root-admin/src/app/lib/util/insert-cookie-in-request.ts
저도 그 방법을 생각했는데, 현재 customFetch가 노드 환경에서 작성되어 있어서 해당 함수에서 next에서 제공하는 cookie 메서드를 사용할 수 없어서 분리한 상황입니다. 

호연님 말씀은 인자로 쿠키 값과 value를 인자로 전달하자는 건가요?

2024-06-09 07:32 UTC, kd02109 commented
- breadcrumb 파일 이름 수정
- UserAction 리펙토링 -> user-state-button-list
- 서버 데이터 revalidate 적용 [참고](https://birdscoders.com/articles/how-to-revalidate-server-components-in-nextjs/)

2024-06-09 08:42 UTC, merged